ARG PLATFORM

FROM --platform=${PLATFORM} docker.io/alpine:3.17.0
LABEL maintainer "Talmai Oliveira <to@talm.ai>, James Addison <jay@jp-hosting.net>"

ARG GROCY_VERSION

# Install build-time dependencies
RUN     apk add --no-cache \
            git \
            gnupg \
            wget \
            yarn

# Install system dependencies
RUN     apk update && \
        apk add --no-cache \
            caddy

# Configure directory permissions
RUN     mkdir /var/www && \
        chown caddy /var/www

COPY static/frontend/Caddyfile /etc/caddy/Caddyfile

# Install application dependencies (unprivileged)
USER caddy
WORKDIR /var/www

# Extract application release package
ENV GROCY_RELEASE_KEY_URI="https://berrnd.de/data/Bernd_Bestel.asc"
RUN     set -o pipefail && \
        export GNUPGHOME=$(mktemp -d) && \
        wget ${GROCY_RELEASE_KEY_URI} -O - | gpg --batch --import && \
        git clone --branch ${GROCY_VERSION} --config advice.detachedHead=false --depth 1 "https://github.com/grocy/grocy.git" . && \
        git verify-commit ${GROCY_VERSION} && \
        rm -rf ${GNUPGHOME}

# Install application dependencies
RUN     yarn install --frozen-lockfile --modules-folder /var/www/public/node_modules --production && \
        yarn cache clean

# Remove build-time dependencies (privileged)
USER root
RUN     apk del \
            git \
            gnupg \
            wget \
            yarn

VOLUME ["/var/lib/caddy"]

EXPOSE 8080

USER caddy

CMD ["caddy", "run", "--config", "/etc/caddy/Caddyfile"]
