FROM alpine:latest
MAINTAINER Talmai Oliveira <to@talm.ai>

RUN     apk update && \
        apk add --no-cache \
            openssl \
            nginx && \
        openssl req \
                -x509 \
                -newkey rsa:2048 \
                -keyout /etc/ssl/private/grocy-nginx.key \
                -out /etc/ssl/private/grocy-nginx.crt \
                -days 365 \
                -nodes \
                -subj /CN=localhost && \
        chown nginx /etc/ssl/private/grocy-nginx.key && \
        chown nginx /etc/ssl/private/grocy-nginx.crt && \
        chown -R nginx /var/log/nginx

COPY docker_nginx /etc/nginx

VOLUME ["/var/log/nginx"]

EXPOSE 8080 8443

USER nginx

ENTRYPOINT ["/usr/sbin/nginx", "-g", "daemon off;"]
