FROM alpine:3.11.5
LABEL maintainer "Talmai Oliveira <to@talm.ai>, James Addison <jay@jp-hosting.net>"

ARG GROCY_VERSION

# Install build-time dependencies
RUN     apk add --no-cache \
            openssl

# Install system dependencies
RUN     apk add --no-cache \
            nginx

# Generate TLS certificates
RUN     openssl req \
                -x509 \
                -newkey rsa:2048 \
                -keyout /etc/ssl/private/grocy-nginx.key \
                -out /etc/ssl/private/grocy-nginx.crt \
                -days 365 \
                -nodes \
                -subj /CN=localhost && \
        chown nginx /etc/ssl/private/grocy-nginx.key && \
        chown nginx /etc/ssl/private/grocy-nginx.crt

# Configure directory permissions
RUN     chown -R nginx /var/log/nginx

COPY docker_nginx/nginx.conf /etc/nginx/nginx.conf
COPY docker_nginx/common.conf /etc/nginx/common.conf
COPY docker_nginx/conf.d/default.conf /etc/nginx/conf.d/default.conf
COPY docker_nginx/conf.d/ssl.conf /etc/nginx/conf.d/ssl.conf

# Remove build-time dependencies
RUN     apk del \
            openssl

VOLUME ["/var/log/nginx"]

EXPOSE 8080 8443

USER nginx

CMD ["nginx", "-g", "daemon off;"]
