FROM alpine:latest
LABEL maintainer "Talmai Oliveira <to@talm.ai>, James Addison <jay@jp-hosting.net>"

RUN     apk update && \
        apk add --no-cache \
            openssl \
            nginx && \
        openssl req \
                -x509 \
                -newkey rsa:2048 \
                -keyout /etc/ssl/private/grocy-nginx.key \
                -out /etc/ssl/private/grocy-nginx.crt \
                -days 365 \
                -nodes \
                -subj /CN=localhost && \
        chown nginx /etc/ssl/private/grocy-nginx.key && \
        chown nginx /etc/ssl/private/grocy-nginx.crt && \
        chown -R nginx /var/log/nginx

COPY docker_nginx/nginx.conf /etc/nginx/nginx.conf
COPY docker_nginx/common.conf /etc/nginx/common.conf
COPY docker_nginx/conf.d/default.conf /etc/nginx/conf.d/default.conf
COPY docker_nginx/conf.d/ssl.conf /etc/nginx/conf.d/ssl.conf

VOLUME ["/var/log/nginx"]

EXPOSE 8080 8443

USER nginx

ENTRYPOINT ["/usr/sbin/nginx", "-g", "daemon off;"]
