FROM php:7.2-fpm-alpine
LABEL maintainer="Talmai Oliveira <to@talm.ai>"

# Optionally authenticate with GitHub using an API token
#
# This can reduce instances of download rate limiting by GitHub
# https://developer.github.com/v3/#rate-limiting
#
# This value is *not* assigned to a variable using the ENV instruction,
# since those variables are persisted in the resulting image and could leak
# developer credentials
# https://docs.docker.com/engine/reference/builder/#env
ARG GITHUB_API_TOKEN

WORKDIR /var/www

# Install system dependencies
RUN     apk update && \
        apk add --no-cache \
            composer \
            yarn \
            git \
            python \
            py-pip \
            wget \
            freetype \
            libpng \
            libjpeg-turbo \
            freetype-dev \
            libpng-dev \
            libjpeg-turbo-dev && \
        docker-php-ext-configure gd \
            --with-gd \
            --with-freetype-dir=/usr/include/ \
            --with-png-dir=/usr/include/ \
            --with-jpeg-dir=/usr/include/ && \
        NPROC=$(grep -c ^processor /proc/cpuinfo 2>/dev/null || 1) && \
        docker-php-ext-install -j${NPROC} gd

# Extract application release package
RUN     wget --header "Authorization: ${GITHUB_API_TOKEN}" -t 3 -T 30 -nv "https://github.com/grocy/grocy/releases/latest/download/grocy.tar.gz" && \
        tar xzf grocy.tar.gz && \
        rm grocy.tar.gz && \
        mv grocy/* . && \
        rm -r grocy-* && \
        mkdir data/viewcache && \
        cp config-dist.php data/config.php && \
        chown -R www-data .

# Install application dependencies
RUN     COMPOSER_OAUTH=${GITHUB_API_TOKEN:+"\"github.com\": \"${GITHUB_API_TOKEN}\""} && \
        COMPOSER_AUTH="{\"github-oauth\": { ${COMPOSER_OAUTH} }}" composer install --no-interaction --no-dev --optimize-autoloader && \
        yarn install --modules-folder /var/www/public/node_modules --production

VOLUME ["/var/www"]

EXPOSE 9000

ENTRYPOINT ["php-fpm", "--nodaemonize"]
