ARG PLATFORM

FROM --platform=${PLATFORM} docker.io/alpine:3.14.0
LABEL maintainer "Talmai Oliveira <to@talm.ai>, James Addison <jay@jp-hosting.net>"

ARG GROCY_VERSION
ARG COMPOSER_VERSION
ARG COMPOSER_CHECKSUM

# ensure www-data user exists
RUN set -eux; \
       adduser -u 82 -D -S -G www-data www-data
# 82 is the standard uid/gid for "www-data" in Alpine
# https://git.alpinelinux.org/aports/tree/main/apache2/apache2.pre-install?h=3.14-stable
# https://git.alpinelinux.org/aports/tree/main/lighttpd/lighttpd.pre-install?h=3.14-stable
# https://git.alpinelinux.org/aports/tree/main/nginx/nginx.pre-install?h=3.14-stable

# Install build-time dependencies
RUN     apk update && \
        apk add --no-cache \
            git \
            gnupg \
            wget

# Install system dependencies
RUN     apk add --no-cache \
            php8 \
            php8-ctype \
            php8-fpm \
            php8-exif \
            php8-fileinfo \
            php8-gd \
            php8-iconv \
            php8-ldap \
            php8-pdo_sqlite \
            php8-simplexml \
            php8-tokenizer \
            php8-phar \
            php8-curl \
            php8-mbstring \
            php8-openssl \
            php8-zip \
            php8-intl

# Link /usr/bin/php to /usr/bin/php8 for universall access to latest php binary. 
# Required by composer, possibly needed by grocy
RUN     ln -s /usr/bin/php8 /usr/bin/php

# Manually install composer.
# As php7 is still the default php version on alpine installing alpine-composer-package would install php7 an add link from /usr/bin/php to /usr/bin/php7.
# This might conflict with grocy if grocy depends on /usr/bin/php linking to /usr/bin/php8
# See: https://gitlab.alpinelinux.org/alpine/aports/-/issues/12308
RUN     wget https://getcomposer.org/download/${COMPOSER_VERSION}/composer.phar -O /tmp/composer.phar && \
        echo "${COMPOSER_CHECKSUM}  /tmp/composer.phar" | sha256sum -c - && \
        mv /tmp/composer.phar /usr/bin/composer && chmod +x /usr/bin/composer

# Configure directory permissions
RUN     chown www-data /var/log/php8 && \
        mkdir /var/www && \
        chown www-data /var/www

COPY docker_backend/www.conf /etc/php8/php-fpm.d/zz-docker.conf

# Install application dependencies (unprivileged)
USER www-data
WORKDIR /var/www

# Extract application release package
ENV GROCY_RELEASE_KEY_URI="https://berrnd.de/data/Bernd_Bestel.asc"
RUN     set -o pipefail && \
        export GNUPGHOME=$(mktemp -d) && \
        wget ${GROCY_RELEASE_KEY_URI} -O - | gpg --batch --import && \
        git clone --branch ${GROCY_VERSION} --config advice.detachedHead=false --depth 1 "https://github.com/grocy/grocy.git" . && \
        git verify-commit ${GROCY_VERSION} && \
        rm -rf ${GNUPGHOME} && \
        mkdir data/viewcache && \
        cp config-dist.php data/config.php

# Install application dependencies
RUN     composer install --no-interaction --no-dev --optimize-autoloader && \
        composer clear-cache

# Remove build-time dependencies (privileged)
USER root
RUN     apk del \
            git \
            gnupg \
            wget

VOLUME ["/var/www/data"]

EXPOSE 9000

USER www-data

CMD ["php-fpm8"]
