{{- $fullName := include "chart.fullname" . -}}
apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/name: {{ $fullName }}
  name: {{ $fullName }}
spec:
  ports:
    - name: "8080"
      port: 8080
      targetPort: 8080
  selector:
    app.kubernetes.io/name: {{ $fullName }}
status:
  loadBalancer: {}
