version: 2
updates:
  - package-ecosystem: "docker"
    directory: "/"
    schedule:
      interval: "daily"
  # Maintain dependencies for GitHub Actions
  # src: https://github.com/marketplace/actions/build-and-push-docker-images#keep-up-to-date-with-github-dependabot
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
