name: grocy docker container

on:
  release:
    types: [published]

jobs:
  build_and_push_latest:
    runs-on: ubuntu-latest
    env:
      GROCY_IMAGE_TAG: ${{ github.event.release.tag_name }}
    steps:
    - uses: actions/checkout@v2
    # Required for the bake-action
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1
    - uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    - name: Build and push
      uses: docker/bake-action@master
      with:
        set: "*.platform=linux/amd64,linux/arm64,linux/arm/v7,linux/arm/v6"
        files: docker-compose.yml
        push: true
